# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LTaxBasemap
                                 A QGIS plugin
 Base map for qgis3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-19
        copyright            : (C) 2021 by Attagorn Srinarong / LTMAP
        email                : attagorn@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LTaxBasemap class from file LTaxBasemap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ltax_basemap import LTaxBasemap
    return LTaxBasemap(iface)
