# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LTaxBasemapDockWidget
                                 A QGIS plugin
 Base map for qgis3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-19
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Attagorn Srinarong / LTMAP
        email                : attagorn@gmail.com
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

#FORM_CLASS, _ = uic.loadUiType(os.path.join(
#    os.path.dirname(__file__), 'ltax_basemap_dockwidget_base.ui'))
from .ltax_basemap_dockwidget_base import Ui_LTaxBasemapDockWidgetBase

class LTaxBasemapDockWidget(QtWidgets.QDockWidget, Ui_LTaxBasemapDockWidgetBase):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(LTaxBasemapDockWidget, self).__init__(parent)
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
